### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Dylan-DPC-zz** [Dylan-DPC/hash-verifier#4]
Create a readme file with necessary information 
Expecting something similar to [this](https://github.com/Dylan-DPC/guzzle-client/blob/master/README.md)

Usage of this package can be found [here](https://github.com/themeanorak/laravel-shopify/blob/master/src/Modules/Auth.php#L53)

**Comment by Braunson** [comment]
I can take care of this for you @Dylan-DPC

**Comment by Braunson** [comment]
I'll take this!

**Comment by Dylan-DPC-zz** [comment]
Completed in #8
