### ISSUE TITLE
Test Setup & Tests

### ISSUE THREAD

**Issue by Dylan-DPC-zz** [Dylan-DPC/hash-verifier#5]
Set up phpunit & other necessary tools (like orchestra if needed).
Write tests (unit & if possible functional or integration). 

Examples of how the package is used can be found [here](https://github.com/themeanorak/laravel-shopify/blob/master/src/Modules/Auth.php#L53)

**Comment by CarmeloNaciti** [comment]
Hi @Dylan-DPC - I'd like to assist in getting the unit tests up-and-running?

**Comment by Dylan-DPC-zz** [comment]
Hey Carmelo. Yeah sure go ahead :+1:
